@charset "utf-8";
/* CSS Document */

body,td,th {font-family: "나눔고딕";font-size: 12px;color: #333;margin-left: 0px;margin-top: 0px;}

a {font-family: "나눔고딕";font-size: 12px;color: #333;}
a:link {text-decoration: none;}
a:visited {text-decoration: none;}
a:hover {text-decoration: none;color: #06F;}
a:active {text-decoration: none;}
.notice_padd {
	padding-top: 26px;
}

a.navi {font-family: "나눔고딕";font-size: 15px;color: #333; font-weight:bold;}
a:link.navi {text-decoration: none;}
a:visited.navi {text-decoration: none;}
a:hover.navi {text-decoration: none;color: #06F;}
a:active.navi {text-decoration: none;}
.notice_padd {
	padding-top: 26px;
}
.notice_padd {
	padding-left: 50px;
}

.list_tit {
	font-family: "굴림";
	font-size: 12px;
	line-height: 21px;
	font-weight: bold;
	color: #000;
}

.list_con {
	font-family: "굴림";
	font-size: 11px;
	line-height: 16px;
	color: #333;
}
.ul {
	padding: 10px;
}

.list {
	list-style-image: url(/chap11/icons/jjum.gif);
	list-style-type: none;
	display:inline-block;
	padding-left:50px;
}
.list2_tit {
	font-family: "굴림";
	font-size: 12px;
	line-height: 21px;
	font-weight: bold;
	color: #3d6d7b;
}

.new_tit {
	font-family: "나눔고딕";
	font-size: 15px;
	font-weight: bold;
	color: #06F;
}